<a href="https://colab.research.google.com/github/SiddharthSinghKushwaha/CDS605_ML_TheoryToCode/blob/main/Confusion_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [10]:
# importing library
import numpy as np

# initialising data

actual = np.array(['man', 'man', 'woman', 'man', 'woman', 'woman', 'woman', 'man', 'man', 'woman'])
predicated = np.array(['woman', 'man', 'woman', 'man', 'woman', 'woman', 'man', 'man', 'woman', 'woman'])
print(actual)
print(predicated)

['man' 'man' 'woman' 'man' 'woman' 'woman' 'woman' 'man' 'man' 'woman']
['woman' 'man' 'woman' 'man' 'woman' 'woman' 'man' 'man' 'woman' 'woman']


In [13]:
# Converting Categorical data into numerical
a = np.zeros(len(actual), dtype='int')
p = np.zeros(len(actual), dtype='int')
for i in range(len(actual)):
  if actual[i] == 'woman':
    a[i] = 1
  if predicated[i] == 'woman':
    p[i] = 1
print(a)
print(p)

[0 0 1 0 1 1 1 0 0 1]
[1. 0. 1. 0. 1. 1. 0. 0. 1. 1.]


In [23]:
# Creating confusion matrix

# tp = np.logical_and(a,p)  [using numpy]

# calculating tp using for loop
tp = tn = fp = fn = 0
for i in range(len(a)):
  if a[i] == 1 and p[i] ==1:
    tp += 1

tn = np.logical_and(a == 0, p == 0)
tn = np.count_nonzero(tn)
fp = np.logical_and(a == 0, p == 1)
fp = np.count_nonzero(fp)
fn = np.logical_and(a == 1, p == 0)
fn = np.count_nonzero(fn)

# confusion matrix
cm = np.array([[tp, fn], [fp, tn]])
print(cm)

[[4 1]
 [2 3]]


In [19]:
# Calculating Accuracy, Precision, Recall and F1-score
acc = (tp+tn)/(tp+tn+fp+fn)
prec = tp/(tp+fp)
rec = tp/(tp+fn)
f1 = 2*prec*rec/(prec+rec)
print("Accuracy = ", round(acc, 2))
print("Precision = ", round(prec, 2))
print("Recall = ", round(rec,2))
print("F1-score = ", round(f1,2))

Accuracy =  0.7
Precision =  0.67
Recall =  0.8
F1-score =  0.73


In [20]:
# True negative rate (Specificity)
tnr = tn/(tn+fp)
print("True negative rate = ", round(tnr,2))

True negative rate =  0.6


# verifying result using Scikit learn

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
cm = confusion_matrix(actual, predicated)
print(cm)
# result is stored in the form of tn, fp, fn, tp

[[3 2]
 [1 4]]


In [26]:
print("Accuracy: ", accuracy_score(a, p))
print("Precision: ", precision_score(a, p))
print("Recall: ", recall_score(a, p))
print("F1-score: ", f1_score(a, p))

Accuracy:  0.7
Precision:  0.6666666666666666
Recall:  0.8
F1-score:  0.7272727272727273
