<a href="https://colab.research.google.com/github/SiddharthSinghKushwaha/CDS605_ML_TheoryToCode/blob/main/Correlation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Program to find corelation among features of the dataset (Class date: 14th Oct)
# import numpy pakage
import numpy as np


In [5]:
# declare four features with 15 data values
f1 = np.array([10,11,10,12,11,10,13,10,12,11,10,11,10,12,11])
f2 = np.array([20,22,19,24,21,20,25,18,23,21,20,22,19,24,21])
f3 = np.array([5,6,5,7,6,5,8,5,7,6,5,6,5,7,6])
f4 = np.array([100,101,100,102,101,100,103,99,102,101,100,101,99,102,101])

In [8]:
# calculating mean of each features
f1_mean = np.round(np.mean(f1), 2)
f2_mean = np.round(np.mean(f2), 2)
f3_mean = np.round(np.mean(f3), 2)
f4_mean = np.round(np.mean(f4), 2)
print(f1_mean, f2_mean, f3_mean, f4_mean)

10.93 21.27 5.93 100.8


In [12]:
# subtracting each feature with its mean
dif_f1_f1mean = f1 - f1_mean
dif_f2_f2mean = f2 - f2_mean
dif_f3_f3mean = f3 - f3_mean
dif_f4_f4mean = f4 - f4_mean
print("Subtract f1 - f1mean", dif_f1_f1mean)
print("Subtract f2 - f2mean", dif_f2_f2mean)
print("Subtract f3 - f3mean", dif_f3_f3mean)
print("Subtract f4 - f4mean", dif_f4_f4mean)

Subtract f1 - f1mean [-0.93  0.07 -0.93  1.07  0.07 -0.93  2.07 -0.93  1.07  0.07 -0.93  0.07
 -0.93  1.07  0.07]
Subtract f2 - f2mean [-1.27  0.73 -2.27  2.73 -0.27 -1.27  3.73 -3.27  1.73 -0.27 -1.27  0.73
 -2.27  2.73 -0.27]
Subtract f3 - f3mean [-0.93  0.07 -0.93  1.07  0.07 -0.93  2.07 -0.93  1.07  0.07 -0.93  0.07
 -0.93  1.07  0.07]
Subtract f4 - f4mean [-0.8  0.2 -0.8  1.2  0.2 -0.8  2.2 -1.8  1.2  0.2 -0.8  0.2 -1.8  1.2
  0.2]


In [15]:
# squaring the prev. calculated differnce
sq_dif_f1_f1mean = dif_f1_f1mean ** 2
sq_dif_f2_f2mean = dif_f2_f2mean ** 2
sq_dif_f3_f3mean = dif_f3_f3mean ** 2
sq_dif_f4_f4mean = dif_f4_f4mean ** 2

# now calculting sum of these square
sum_sq_dif_f1_f1mean = np.round(np.sum(sq_dif_f1_f1mean), 2)
sum_sq_dif_f2_f2mean = np.round(np.sum(sq_dif_f2_f2mean), 2)
sum_sq_dif_f3_f3mean = np.round(np.sum(sq_dif_f3_f3mean), 2)
sum_sq_dif_f4_f4mean = np.round(np.sum(sq_dif_f4_f4mean), 2)

print(sum_sq_dif_f1_f1mean, sum_sq_dif_f2_f2mean, sum_sq_dif_f3_f3mean, sum_sq_dif_f4_f4mean)

12.93 58.93 12.93 18.4


In [16]:
# product of dif_f1_f1_mean and dif_f2_f2_mean and other 5 more cases
product_f1_f2 = dif_f1_f1mean * dif_f2_f2mean
product_f1_f3 = dif_f1_f1mean * dif_f3_f3mean
product_f1_f4 = dif_f1_f1mean * dif_f4_f4mean
product_f2_f3 = dif_f2_f2mean * dif_f3_f3mean
product_f2_f4 = dif_f2_f2mean * dif_f4_f4mean
product_f3_f4 = dif_f3_f3mean * dif_f4_f4mean

# sum of these product of feature
sum_product_f1_f2 = np.round(np.sum(product_f1_f2), 2)
sum_product_f1_f3 = np.round(np.sum(product_f1_f3), 2)
sum_product_f1_f4 = np.round(np.sum(product_f1_f4), 2)
sum_product_f2_f3 = np.round(np.sum(product_f2_f3), 2)
sum_product_f2_f4 = np.round(np.sum(product_f2_f4), 2)
sum_product_f3_f4 = np.round(np.sum(product_f3_f4), 2)

print(sum_product_f1_f2, sum_product_f1_f3, sum_product_f1_f4, sum_product_f2_f3, sum_product_f2_f4, sum_product_f3_f4)

26.27 12.93 14.8 26.27 31.8 14.8


In [17]:
# calculating correlation for 6 cases
corr_f1_f2 = np.round(sum_product_f1_f2 / np.sqrt(sum_sq_dif_f1_f1mean * sum_sq_dif_f2_f2mean), 2)
corr_f1_f3 = np.round(sum_product_f1_f3 / np.sqrt(sum_sq_dif_f1_f1mean * sum_sq_dif_f3_f3mean), 2)
corr_f1_f4 = np.round(sum_product_f1_f4 / np.sqrt(sum_sq_dif_f1_f1mean * sum_sq_dif_f4_f4mean), 2)
corr_f2_f3 = np.round(sum_product_f2_f3 / np.sqrt(sum_sq_dif_f2_f2mean * sum_sq_dif_f3_f3mean), 2)
corr_f2_f4 = np.round(sum_product_f2_f4 / np.sqrt(sum_sq_dif_f2_f2mean * sum_sq_dif_f4_f4mean), 2)
corr_f3_f4 = np.round(sum_product_f3_f4 / np.sqrt(sum_sq_dif_f3_f3mean * sum_sq_dif_f4_f4mean), 2)

print("Cor(F1, F2)", corr_f1_f2)
print("Cor(F1, F3)", corr_f1_f3)
print("Cor(F1, F4)", corr_f1_f4)
print("Cor(F2, F3)", corr_f2_f3)
print("Cor(F2, F4)", corr_f2_f4)
print("Cor(F3, F4)", corr_f3_f4)

Cor(F1, F2) 0.95
Cor(F1, F3) 1.0
Cor(F1, F4) 0.96
Cor(F2, F3) 0.95
Cor(F2, F4) 0.97
Cor(F3, F4) 0.96


In [ ]:
# based on the correlation, I can discard F1 or F3 if threshold is 0.98 (Filter Method)

## Above correlation code using GEMINI

Following is been generated by Gemini. I trying how it can perform the same task.

In [18]:
import pandas as pd

data = {'f1': f1, 'f2': f2, 'f3': f3, 'f4': f4}
df = pd.DataFrame(data)
display(df.head())

f1  f2  f3   f4
0  10  20   5  100
1  11  22   6  101
2  10  19   5  100
3  12  24   7  102
4  11  21   6  101

In [19]:
feature_means = df.mean()
print(feature_means)

f1     10.933333
f2     21.266667
f3      5.933333
f4    100.800000
dtype: float64


In [20]:
df_diff = df - feature_means
display(df_diff.head())

f1        f2        f3   f4
0 -0.933333 -1.266667 -0.933333 -0.8
1  0.066667  0.733333  0.066667  0.2
2 -0.933333 -2.266667 -0.933333 -0.8
3  1.066667  2.733333  1.066667  1.2
4  0.066667 -0.266667  0.066667  0.2

In [21]:
df_diff_squared = df_diff ** 2
sum_of_squared_differences = df_diff_squared.sum()
print(sum_of_squared_differences)

f1    12.933333
f2    58.933333
f3    12.933333
f4    18.400000
dtype: float64


In [22]:
product_of_differences = df_diff.T.dot(df_diff)
sum_of_product_of_differences = product_of_differences.values
print(sum_of_product_of_differences)

[[12.93333333 26.26666667 12.93333333 14.8       ]
 [26.26666667 58.93333333 26.26666667 31.8       ]
 [12.93333333 26.26666667 12.93333333 14.8       ]
 [14.8        31.8        14.8        18.4       ]]


In [23]:
sqrt_sum_of_squared_differences = np.sqrt(sum_of_squared_differences)
outer_product_of_sqrt = np.outer(sqrt_sum_of_squared_differences, sqrt_sum_of_squared_differences)
correlation_matrix = sum_of_product_of_differences / outer_product_of_sqrt
print(correlation_matrix)

[[1.         0.95141331 1.         0.95939526]
 [0.95141331 1.         0.95141331 0.96568994]
 [1.         0.95141331 1.         0.95939526]
 [0.95939526 0.96568994 0.95939526 1.        ]]


In [24]:
correlation_matrix_df = pd.DataFrame(correlation_matrix, columns=df.columns, index=df.columns)
display(correlation_matrix_df)

f1        f2        f3        f4
f1  1.000000  0.951413  1.000000  0.959395
f2  0.951413  1.000000  0.951413  0.965690
f3  1.000000  0.951413  1.000000  0.959395
f4  0.959395  0.965690  0.959395  1.000000

Data Analysis Key Findings

*   The correlation matrix shows the pairwise correlation coefficients between each feature.
