<a href="https://colab.research.google.com/github/SiddharthSinghKushwaha/CDS605_ML_TheoryToCode/blob/main/knn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# import library
import numpy as np

In [2]:
# input: 15 data points of 2D coordinates (x1, x2)
input_data = np.array([[2,10], [2,6], [11,11], [6,9], [6,5], [1,2], [5,10], [6,11], [3,10], [3,8]])
class_label = ['C2', 'C1', 'C3', 'C2', 'C1', 'C1', 'C2', 'C2', 'C2', 'C2' ]

In [3]:
# converting c1 to 0, c2 to 1 and c3 to 2
for i in range(len(class_label)):
    if class_label[i] == 'C1':
        class_label[i] = 0
    elif class_label[i] == 'C2':
        class_label[i] = 1
    else:
        class_label[i] = 2

In [4]:
# to find the class label for P(5,7)
test_point = np.array([5,7])

# Using manhantten distance formula
distance = np.sum(np.abs(input_data - test_point), axis=1)
print(distance)

[ 6  4 10  3  3  9  3  5  5  3]


In [5]:
# to combine distance with their respective class_label
combined = np.column_stack((distance, class_label))
print(combined)

[[ 6  1]
 [ 4  0]
 [10  2]
 [ 3  1]
 [ 3  0]
 [ 9  0]
 [ 3  1]
 [ 5  1]
 [ 5  1]
 [ 3  1]]


In [6]:
# suppose k = 3
# picking top 3 class label
k = int(input("Enter the value of k: "))

combined = combined[combined[:, 0].argsort()][:k]
print(combined)

Enter the value of k: 4
[[3 1]
 [3 0]
 [3 1]
 [3 1]]


In [7]:
# calculating the majority of class and printing the Class label it belong to
countC1=countC2=countC3=0
for i in range(k):
    if combined[i][1] == 0:
        countC1 += 1
    elif combined[i][1] == 1:
        countC2 += 1
    else:
        countC3 += 1

In [8]:
if countC1 > countC2 and countC1 > countC3:
    print("Class label of P(5,7) is C1")
elif countC2 > countC1 and countC2 > countC3:
    print("Class label of P(5,7) is C2")
else:
    print("Class label of P(5,7) is C3")

Class label of P(5,7) is C2
