<a href="https://colab.research.google.com/github/SiddharthSinghKushwaha/CDS605_ML_TheoryToCode/blob/main/MLR_ML_L5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Python Implementation of **Multiple Regression (MLR)**. Implementing the solved example. CLass date: Aug 21,2025.

In [22]:
# importing numpy library
import numpy as np

# Initializing X 2D matrix and Y vector
X = np.array([[1,1,2],
              [1,2,0], [1,3,1]])
Y = np.array([4,3,5])
print(X)
print(Y)

[[1 1 2]
 [1 2 0]
 [1 3 1]]
[4 3 5]


In [23]:
# Transpose of matrix X
X_T = X.T
print(X_T)

[[1 1 1]
 [1 2 3]
 [2 0 1]]


In [24]:
# multiplying X_T and X
X_T_X = np.dot(X_T,X)
print(X_T_X)

# result will be always Symmetric matrix (equals to its transpose)

[[ 3  6  3]
 [ 6 14  5]
 [ 3  5  5]]


In [25]:
# determinat of X_T_X
det_X_T_X = round(np.linalg.det(X_T_X),2)
print(det_X_T_X)

9.0


In [26]:
# inverse of X_T_X
inv_X_T_X = np.linalg.inv(X_T_X)
print(inv_X_T_X)

[[ 5.         -1.66666667 -1.33333333]
 [-1.66666667  0.66666667  0.33333333]
 [-1.33333333  0.33333333  0.66666667]]


In [27]:
# dot product of X_T and Y
X_T_Y = np.dot(X_T,Y)
print(X_T_Y)

[12 25 13]


In [28]:
# dot product of inv_X_T_X and X_T_Y
B = np.dot(inv_X_T_X,X_T_Y)
print(B)

[1. 1. 1.]


In [29]:
# final multiple regression equation y = B0 + B1x1 + B2x2
for i in range(len(B)):
  if i == 0:
    print(f"y = {round(B[i])}",end=" ")
  else:
    print(f"+ {round(B[i])}.x{i}",end=" ")

y = 1 + 1.x1 + 1.x2 

Polynomial Regression

In [18]:
# importing numpy library
import numpy as np

# Initializing X matrix and Y vector
X = np.array([[1,1,1],
              [1,2,4], [1,3,9], [1,4,16]])
Y = np.array([6,11,18,27])
print(X)
print(Y)

# Transpose of matrix X
X_T = X.T
print(X_T)

# multiplying X_T and X
X_T_X = np.dot(X_T,X)
print(X_T_X)

# result will be always Symmetric matrix (equals to its transpose)
# determinat of X_T_X
det_X_T_X = round(np.linalg.det(X_T_X),2)
print(det_X_T_X)

# inverse of X_T_X
inv_X_T_X = np.linalg.inv(X_T_X)
print(inv_X_T_X)

# dot product of X_T and Y
X_T_Y = np.dot(X_T,Y)
print(X_T_Y)

# dot product of inv_X_T_X and X_T_Y
B = np.dot(inv_X_T_X,X_T_Y)
print(B)

[[ 1  1  1]
 [ 1  2  4]
 [ 1  3  9]
 [ 1  4 16]]
[ 6 11 18 27]
[[ 1  1  1  1]
 [ 1  2  3  4]
 [ 1  4  9 16]]
[[  4  10  30]
 [ 10  30 100]
 [ 30 100 354]]
80.0
[[ 7.75 -6.75  1.25]
 [-6.75  6.45 -1.25]
 [ 1.25 -1.25  0.25]]
[ 62 190 644]
[3. 2. 1.]


In [21]:
# final polynomial regression equation y = B0 + B1x1 + B2x2 + ... + BnXn
for i in range(len(B)):
  if i == 0:
    print(f"y = {round(B[i])}",end=" ")
  else:
    print(f"+ {round(B[i])}.x{i}",end=" ")

y = 3 + 2.x1 + 1.x2 