<a href="https://colab.research.google.com/github/SiddharthSinghKushwaha/CDS605_ML_TheoryToCode/blob/main/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PCA - Principal Component Analysis

In [31]:
# import numpy
import numpy as np

In [32]:
# create a 5x3 matrix
x = np.array([[2,0,1],[0,2,3],[3,1,2],[1,3,0],[2,2,1]])
print(x)
# calculating column mean
col_mean = np.mean(x,axis=0)
print(col_mean)

[[2 0 1]
 [0 2 3]
 [3 1 2]
 [1 3 0]
 [2 2 1]]
[1.6 1.6 1.4]


In [33]:
# subtracting column mean form each elements
x_mean = x - col_mean
print(x_mean)

[[ 0.4 -1.6 -0.4]
 [-1.6  0.4  1.6]
 [ 1.4 -0.6  0.6]
 [-0.6  1.4 -1.4]
 [ 0.4  0.4 -0.4]]


In [34]:
# calculating covariance matrix c = 1/(n-1)x_mean_transpose x x_mean
c = np.dot(x_mean.T,x_mean)
print(c)
c = c/(x.shape[0]-1)
print(c)

[[ 5.2 -2.8 -1.2]
 [-2.8  5.2 -1.2]
 [-1.2 -1.2  5.2]]
[[ 1.3 -0.7 -0.3]
 [-0.7  1.3 -0.3]
 [-0.3 -0.3  1.3]]


In [35]:
# to find eigen  values
eigen_values,eigen_vectors = np.linalg.eig(c)
eigen_values = np.sort(eigen_values)[::-1]
print(eigen_values)
print(eigen_vectors)

[2.  1.5 0.4]
[[ 6.39602149e-01  7.07106781e-01 -3.01511345e-01]
 [ 6.39602149e-01 -7.07106781e-01 -3.01511345e-01]
 [ 4.26401433e-01 -1.14298606e-16  9.04534034e-01]]


In [36]:
# to arrange the eigen vectors in the order of eigen values
#eigen_vectors = eigen_vectors[:,eigen_values.argsort()[::-1]]

In [37]:
# to calculate z=x_mean X eigen vectors to find the princpal component
z = np.dot(x_mean,eigen_vectors)
print(z)

[[-9.38083152e-01  1.41421356e+00  9.14409911e-17]
 [-8.52802865e-02 -1.41421356e+00  1.80906807e+00]
 [ 7.67522579e-01  1.41421356e+00  3.01511345e-01]
 [-8.52802865e-02 -1.41421356e+00 -1.50755672e+00]
 [ 3.41121146e-01 -2.13441537e-16 -6.03022689e-01]]


In [38]:
z = np.round(z,2)
print(z)

[[-0.94  1.41  0.  ]
 [-0.09 -1.41  1.81]
 [ 0.77  1.41  0.3 ]
 [-0.09 -1.41 -1.51]
 [ 0.34 -0.   -0.6 ]]


## Questions 2

In [39]:
# perform all the same operations with the new array
x = np.array([[2,0], [0,2], [3,1], [1,3], [2,2]])
print(x)

[[2 0]
 [0 2]
 [3 1]
 [1 3]
 [2 2]]


In [40]:
# calculating column mean
col_mean = np.mean(x,axis=0)
print(col_mean)

[1.6 1.6]


In [41]:
# subtracting column mean form each elements
x_mean = x - col_mean
print(x_mean)

[[ 0.4 -1.6]
 [-1.6  0.4]
 [ 1.4 -0.6]
 [-0.6  1.4]
 [ 0.4  0.4]]


In [42]:
# calculating covariance matrix c = 1/(n-1)x_mean_transpose x x_mean
c = np.dot(x_mean.T,x_mean)
print(c)
c = c/(x.shape[0]-1)
print(c)

[[ 5.2 -2.8]
 [-2.8  5.2]]
[[ 1.3 -0.7]
 [-0.7  1.3]]


In [43]:
# to find eigen  values
eigen_values,eigen_vectors = np.linalg.eig(c)
eigen_values = np.sort(eigen_values)[::-1]
print(eigen_values)
print(eigen_vectors)

[2.  0.6]
[[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]


In [44]:
# to calculate z=x_mean X eigen vectors to find the princpal component
z = np.dot(x_mean,eigen_vectors)
print(z)

[[ 8.48528137e-01  1.41421356e+00]
 [ 8.48528137e-01 -1.41421356e+00]
 [-5.65685425e-01  1.41421356e+00]
 [-5.65685425e-01 -1.41421356e+00]
 [-5.65685425e-01 -7.04230646e-17]]


In [45]:
# represent z values in two decimal places
z = np.round(z,2)
print(z)

[[ 0.85  1.41]
 [ 0.85 -1.41]
 [-0.57  1.41]
 [-0.57 -1.41]
 [-0.57 -0.  ]]
