## Numpy Practice Problems

In [ ]:
# 1. Create a NumPy array containing numbers 0-9
import numpy as np
arr1 = np.arange(10)
print(arr1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 2. Generate a 3x3 matrix with values ranging from 2 to 10
arr2 = np.arange(2,11).reshape(3,3)
print(arr2)

[[ 2  3  4]
 [ 5  6  7]
 [ 8  9 10]]


In [ ]:
# 3. Create an array of 10 zeroes and set the fifth value to 1
arr3 = np.zeros(10)
arr3[4] = 1
print(arr3)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
# 4. Reverse a NumPy array without using loops
arr4 = np.array([71,22,36,42,58])
arr4 = arr4[::-1]
print(arr4)

[58 42 36 22 71]


In [ ]:
# 5. Create a 3x3 identity matrix
arr5 = np.identity(3)
print(arr5)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# 6. Generate an array of 9 random integers between 1 and 100, and reshape it to 3x3
arr6 = np.random.randint(1,100,9).reshape(3,3)
print(arr6)

[[30 60  1]
 [94  6 80]
 [25 38 30]]


In [ ]:
# 7. Find the maximum, minimum, and mean of a given array
arr7 = np.array([56, 78, 34, 22, 90, 55, 34])
print(np.max(arr7))
print(np.min(arr7))
print(np.round(np.mean(arr7),2))

90
22
52.71


In [ ]:
# 8. Replace all the odd numbers in an array with -1
arr8 = np.array([22, 67, 54, 34, 99, 60, 33])
arr8[arr8%2 != 0] = -1    # boolean indexing
print(arr8)

# Q8 using loop
arr8_2 = np.array([22, 67, 54, 34, 99, 60, 33])
for i in range(len(arr8_2)):
    if arr8_2[i]%2 != 0:
        arr8_2[i] = -1
print(arr8_2)

# Q8 using list comprehension
arr8_3 = np.array([22, 67, 54, 34, 99, 60, 33])
arr8_3 = np.array([x if x%2 == 0 else -1 for x in arr8_3])
print(arr8_3)

[22 -1 54 34 -1 60 -1]
[22 -1 54 34 -1 60 -1]
[22 -1 54 34 -1 60 -1]


In [ ]:
# 9. Create a 5x5 matrix values from 1 to 25, and extract the middle 3x3 submatrix
arr9 = np.arange(1,26).reshape(5,5)
print(arr9)
arr9_middle = arr9[1:4,1:4]
print(arr9_middle)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]


In [ ]:
# 10. Normalize a random 1D array (subtract mean, divide by std)
arr10 = np.random.randint(1,100,10)
arr10_mean = np.mean(arr10)
arr10_std = np.std(arr10)
arr10_norm = (arr10 - arr10_mean)/arr10_std
print(arr10_norm)

[ 1.52011375 -0.37638133 -0.52226557  0.00291768 -1.2808636   0.81986941
 -1.19333306 -1.10580252  0.9365768   1.19916843]


In [ ]:
# 11. Stack two 2x2 matrices vertically and horizontally
matrix1 = np.array([[1,5], [2, 4]])
matrix2 = np.array([[4,8], [3, 9]])
print(np.vstack((matrix1, matrix2)))
print(np.hstack((matrix1, matrix2)))

[[1 5]
 [2 4]
 [4 8]
 [3 9]]
[[1 5 4 8]
 [2 4 3 9]]


In [ ]:
# 12. Create an array with random values and sort it in descending order
arr12 = np.random.randint(1,100,10)
arr12 = np.sort(arr12)[::-1] # (sort + reverse)it return a new sorted array
print(arr12)

[83 80 76 39 35 34 30 30 29 23]


In [ ]:
# 13. Given two arrays, compute their element-wise product and dot product.
arr13_1 = np.array([1,2,3])
arr13_2 = np.array([4,5,6])
print(np.multiply(arr13_1,arr13_2))
print(np.dot(arr13_1,arr13_2))

[ 4 10 18]
32


In [ ]:
# 14. Use Boolean indexing to select all even numbers from an array.
arr14 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr14 = arr14[arr14%2 == 0]
print(arr14)

[2 4 6 8]


In [ ]:
# 15. Create a 10x10 matrix and fill its border with 1s and the inside with 0s
arr15 = np.zeros((10,10))
arr15[0,:] = 1
arr15[-1,:] = 1
arr15[:,0] = 1
arr15[:,-1] = 1
print(arr15)

# using loop
arr15_2 = np.zeros((10,10))
for i in range(0,10):
    for j in range(0,10):
      if i == 0 or i == 9 or j == 0 or j == 9:
        arr15_2[i,j] = 1
print(arr15_2)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
# 16. Compute the Euclidean distance between two random 3D points using NumPy only.
point1 = np.random.randint(1,10,3)
point2 = np.random.randint(1,10,3)
diff_sq = (point1 - point2)**2
print(np.round(np.sqrt(np.sum(diff_sq)),2))

8.06


In [ ]:
# 17. Generate a random 5x5 matrix and compute its determinant and inverse.
matrix = np.random.randint(1,10,25).reshape(5,5)
print(matrix)
print(np.linalg.det(matrix))
print(np.linalg.inv(matrix))

[[9 2 2 5 8]
 [8 5 3 9 9]
 [9 3 1 1 8]
 [2 7 5 1 3]
 [3 8 7 9 7]]
1343.9999999999989
[[ 0.35267857  0.20014881 -0.36904762  0.36681548 -0.39583333]
 [-0.32589286  0.38467262  0.01190476  0.21800595 -0.22916667]
 [ 0.51339286 -0.45758929 -0.17857143  0.04241071  0.1875    ]
 [ 0.04017857  0.21056548 -0.20238095  0.04389881 -0.10416667]
 [-0.34375    -0.33854167  0.58333333 -0.50520833  0.52083333]]


In [ ]:
# 18. Replace all NaN values in an array with the column mean. (row mean)
arr18 = np.array([1, 2, np.nan, 4, 5, np.nan, 7, 8, 9])
arr18_mean = np.nanmean(arr18)
arr18[np.isnan(arr18)] = arr18_mean
print(arr18)

[1.         2.         5.14285714 4.         5.         5.14285714
 7.         8.         9.        ]


In [ ]:
# 19. Given a matrix, find its eigenvalues and eigenvectors.
matrix = np.array([[1, 2], [3, 4]])
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# 20. Simulate rolling two dice 1000 times and compute the frequency of each sum (2–12).
numbers = np.arange(2,13)
count = np.zeros(12)
frequency = {int(num): int(cnt) for num, cnt in zip(numbers, count)}
for i in range(1000):
  dice1 = np.random.randint(1,7)
  dice2 = np.random.randint(1,7)
  sumOfdice = dice1+dice2
  frequency[sumOfdice] = frequency.get(sumOfdice,0)+1

print(frequency)


{2: 32, 3: 54, 4: 78, 5: 116, 6: 145, 7: 174, 8: 137, 9: 117, 10: 74, 11: 56, 12: 17}


In [61]:
# 21. Save a NumPy array to disk and reload it from a .npy file.
arr = np.random.randint(1,100,10)
print(arr)
np.save('array.npy', arr)
array_loaded = np.load('array.npy')
print(array_loaded)

[84 96 38 66 48 43 19 53 50 93]
[84 96 38 66 48 43 19 53 50 93]
